export enum WINDOW_MESSAGES {
  REPORT_HEIGHT = 'REPORT_HEIGHT',
  CLOSE = 'CLOSE',
  CONNECTED = 'CONNECTED',
  TRANSACTION_COMPLETE = 'TRANSACTION_COMPLETE',
  TRANSACTION_FAILED = 'TRANSACTION_FAILED',
}
